---
dependencies: []

galaxy_info:
  role_name: basic_config
  author: Nils Ost (@nils-ost)
  description: configures Nginx Proxy Manager with basic capabilities
  license: GPL-3.0-or-later
  min_ansible_version: 2.13.9
  galaxy_tags:
    - nginxproxymanager
    - npm
    - web
    - containers
    - docker
    - compose
    - server
