---
dependencies: []

galaxy_info:
  role_name: install_with_docker
  author: Nils Ost (@nils-ost)
  description: installs Nginx Proxy Manager as a docker container with the help of compose
  license: GPL-3.0-or-later
  min_ansible_version: 2.13.9
  galaxy_tags:
    - nginxproxymanager
    - npm
    - web
    - containers
    - docker
    - compose
    - server
